### ISSUE TITLE
Collection of HDMI pmod designs

### ISSUE THREAD

**Issue by mithro** [projf/hardware-support#2]
I have a whole bunch of HDMI designs in KiCAD files. I have also used these templates to create a bunch of HDMI pmod options. This should make it easy for people to make their own boards and adapters.

 * https://github.com/mithro/HDMI2USB-kicad-templates/tree/master/hdmi
 * https://github.com/mithro/pmod-hdmi

**Comment by WillGreen** [comment]
Thanks, I'll take a look. 
Though I'm not building new PCBs just now as I'm focused on HDL.
